### ISSUE TITLE
KTP faceted search

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#487]
KTPs are currently [shown by embedding landscape](https://www.cncf.io/certification/kubernetes-training-partners/).  KTPs have requested a more engaging search experience.  They want to allow users to search for them by:
- CNCF certification <list all - select one>
- Region <global, North America, South America, etc - select one.>
- Delivery <e-learning, instructor-led, both - select one>
- CNCF Projects <Kafka, etc. - select multiple>

The listing should allow the partner to write their own 1-2 sentence blurb, link to partner-selected page, include partner-selected social page links etc.  All this data can be managed in landscape and pulled from there, similar to how we do with projects.

**Comment by SWilliamsOteemo** [comment]
Add multiple as options for CNCF certification and Region.

**Comment by xmulligan** [comment]
I think that means select multiple options @cjyabraham

**Comment by cjyabraham** [comment]
@xmulligan Do you have suggestions as to how we'll initially gather all the metadata for each of the KTPs?  Send an email out and invite them to edit [the landscape.yml file](https://github.com/cncf/landscape/blob/master/landscape.yml)?  We may need to provide them with a list of possible values for each field so that we have consistent sets of values.

**Comment by cjyabraham** [comment]
Also, are "CNCF Technologies" the same thing as "CNCF Projects"?

**Comment by xmulligan** [comment]
@cjyabraham that sounds like the right approach.  

> @xmulligan Do you have suggestions as to how we'll initially gather all the metadata for each of the KTPs? Send an email out and invite them to edit [the landscape.yml file](https://github.com/cncf/landscape/blob/master/landscape.yml)? We may need to provide them with a list of possible values for each field so that we have consistent sets of values.

**Comment by xmulligan** [comment]
> Also, are "CNCF Technologies" the same thing as "CNCF Projects"?

I don't think we should add this section as it would add a lot of complexity without a major benefit

**Comment by AndreyKozlov1984** [comment]
I've added a support for custom validation of extra properties in the landscape.yml file
An example pull request - https://github.com/cncf/landscape/pull/2348
As you can see, `Akri reports: Test error` because of the custom `validator` field in the `settings.yml` file

**Comment by AndreyKozlov1984** [comment]
The validator is a piece of javascript code which uses `field`, `value` and `error` variables and it is applied to every custom property of every item

https://github.com/cncf/landscape/pull/2348/files#diff-6167ce9ac9bedafca7114a29ba4fba1ad953b7e6006a3dff08e3272c1866128bR26

**Comment by cjyabraham** [comment]
> > Also, are "CNCF Technologies" the same thing as "CNCF Projects"?
> 
> I don't think we should add this section as it would add a lot of complexity without a major benefit

Where is the complexity?  I'm not sure I see the problem...

**Comment by cjyabraham** [comment]
I figure we could go with the following format:
```
          - item:
            name: PRODYNA (KTP)
            description: PRODYNA designs, implements, and operates Kubernetes-based custom applications for mid- to large size enterprises in all of Europe.
            homepage_url: https://www.prodyna.com/en/cloud-native-computing-docker-kubernetes
            logo: prodyna.svg
            crunchbase: https://www.crunchbase.com/organization/prodyna
            extra:
              training_projects: the-update-framework-tuf, prometheus, operator-framework
              training_certifications: cka, cks, kcna
              training_type: e-learning, instructor
```

Note that training_projects should match a url slug from the [CNCF.io projects listing](https://www.cncf.io/projects/).  Does this work?
